name: pyspark-interactive-lecture
channels:
- damianavila82
- conda-forge
- defaults
dependencies:
- python=3.5
- requests
- rise=5
- pip:
  - invoke==0.22.0
  - patool
  - path.py
  - psutil
  - pyspark==2.2.0.post0