name: pyspark-interactive-lecture
channels:
  - defaults
  - conda-forge
dependencies:
  - invoke
  - jupyter
  - numpy
  - path.py
  - psutil
  - pyspark=2.3.2
  - python=3.6
  - rise=5
  - pip:
      - nclib
      - wget
