name: pyspark-interactive-lecture
channels:
- damianavila82
- conda-forge
- defaults
dependencies:
- jupyterlab
- numpy
- python=3
- requests
- rise=5
- pip:
  - invoke
  - nclib
  - patool
  - path.py
  - psutil
  - pyspark==2.2.0.post0