name: pyspark-interactive-lecture
channels:
- damianavila82
- conda-forge
- defaults
dependencies:
- invoke
- jupyterlab
- numpy
- path.py
- psutil
- pyspark
- python=3
- requests
- rise=5
- pip:
  - nclib
  